"""add domain tables

Revision ID: 4b5c6a12bd75
Revises: 
Create Date: 2026-01-27 16:16:54.996989

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b5c6a12bd75'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title_ko', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_ko', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mission_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_type')
    )
    op.create_index(op.f('ix_mission_templates_is_active'), 'mission_templates', ['is_active'], unique=False)
    op.create_table('phrases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_ko', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrases_category'), 'phrases', ['category'], unique=False)
    op.create_index(op.f('ix_phrases_is_active'), 'phrases', ['is_active'], unique=False)
    op.create_index(op.f('ix_phrases_usage_count'), 'phrases', ['usage_count'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('mission_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('mission_template_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_template_id'], ['mission_templates.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_progress_created_at'), 'mission_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_mission_progress_mission_template_id'), 'mission_progress', ['mission_template_id'], unique=False)
    op.create_index(op.f('ix_mission_progress_profile_id'), 'mission_progress', ['profile_id'], unique=False)
    op.create_index(op.f('ix_mission_progress_status'), 'mission_progress', ['status'], unique=False)
    op.create_table('mission_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_template_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title_ko', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_ko', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_template_id'], ['mission_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_steps_mission_template_id'), 'mission_steps', ['mission_template_id'], unique=False)
    op.create_table('route_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('start_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('end_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=False),
    sa.Column('end_lng', sa.Float(), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=True),
    sa.Column('route_option', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_distance_m', sa.Integer(), nullable=False),
    sa.Column('total_duration_s', sa.Integer(), nullable=False),
    sa.Column('path_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_history_created_at'), 'route_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_history_profile_id'), 'route_history', ['profile_id'], unique=False)
    op.create_table('mission_step_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_progress_id', sa.Uuid(), nullable=False),
    sa.Column('mission_step_id', sa.Uuid(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_progress_id'], ['mission_progress.id'], ),
    sa.ForeignKeyConstraint(['mission_step_id'], ['mission_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_step_progress_mission_progress_id'), 'mission_step_progress', ['mission_progress_id'], unique=False)
    op.create_index(op.f('ix_mission_step_progress_mission_step_id'), 'mission_step_progress', ['mission_step_id'], unique=False)
    op.create_table('phrase_step_mapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phrase_id', sa.Uuid(), nullable=False),
    sa.Column('mission_step_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_step_id'], ['mission_steps.id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_step_mapping_mission_step_id'), 'phrase_step_mapping', ['mission_step_id'], unique=False)
    op.create_index(op.f('ix_phrase_step_mapping_phrase_id'), 'phrase_step_mapping', ['phrase_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translated_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_lang', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('target_lang', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('translation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mission_progress_id', sa.Uuid(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_progress_id'], ['mission_progress.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_created_at'), 'translations', ['created_at'], unique=False)
    op.create_index(op.f('ix_translations_profile_id'), 'translations', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_profile_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_created_at'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_phrase_step_mapping_phrase_id'), table_name='phrase_step_mapping')
    op.drop_index(op.f('ix_phrase_step_mapping_mission_step_id'), table_name='phrase_step_mapping')
    op.drop_table('phrase_step_mapping')
    op.drop_index(op.f('ix_mission_step_progress_mission_step_id'), table_name='mission_step_progress')
    op.drop_index(op.f('ix_mission_step_progress_mission_progress_id'), table_name='mission_step_progress')
    op.drop_table('mission_step_progress')
    op.drop_index(op.f('ix_route_history_profile_id'), table_name='route_history')
    op.drop_index(op.f('ix_route_history_created_at'), table_name='route_history')
    op.drop_table('route_history')
    op.drop_index(op.f('ix_mission_steps_mission_template_id'), table_name='mission_steps')
    op.drop_table('mission_steps')
    op.drop_index(op.f('ix_mission_progress_status'), table_name='mission_progress')
    op.drop_index(op.f('ix_mission_progress_profile_id'), table_name='mission_progress')
    op.drop_index(op.f('ix_mission_progress_mission_template_id'), table_name='mission_progress')
    op.drop_index(op.f('ix_mission_progress_created_at'), table_name='mission_progress')
    op.drop_table('mission_progress')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_phrases_usage_count'), table_name='phrases')
    op.drop_index(op.f('ix_phrases_is_active'), table_name='phrases')
    op.drop_index(op.f('ix_phrases_category'), table_name='phrases')
    op.drop_table('phrases')
    op.drop_index(op.f('ix_mission_templates_is_active'), table_name='mission_templates')
    op.drop_table('mission_templates')
    # ### end Alembic commands ###
