"""fix FK constraints with proper ON DELETE rules

Revision ID: b5d7e3f4a891
Revises: 4b5c6a12bd75
Create Date: 2026-01-27 17:00:00.000000

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5d7e3f4a891'
down_revision: str | Sequence[str] | None = '4b5c6a12bd75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add proper ON DELETE rules to all foreign keys."""
    # Drop existing FKs and recreate with ON DELETE rules
    # Note: FK names are auto-generated by SQLAlchemy as {table}_{column}_fkey

    # 1. translations table
    op.drop_constraint('translations_profile_id_fkey', 'translations', type_='foreignkey')
    op.create_foreign_key(
        'translations_profile_id_fkey', 'translations', 'profiles',
        ['profile_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint('translations_mission_progress_id_fkey', 'translations', type_='foreignkey')
    op.create_foreign_key(
        'translations_mission_progress_id_fkey', 'translations', 'mission_progress',
        ['mission_progress_id'], ['id'], ondelete='SET NULL'
    )

    # 2. mission_progress table
    op.drop_constraint('mission_progress_profile_id_fkey', 'mission_progress', type_='foreignkey')
    op.create_foreign_key(
        'mission_progress_profile_id_fkey', 'mission_progress', 'profiles',
        ['profile_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint('mission_progress_mission_template_id_fkey', 'mission_progress', type_='foreignkey')
    op.create_foreign_key(
        'mission_progress_mission_template_id_fkey', 'mission_progress', 'mission_templates',
        ['mission_template_id'], ['id'], ondelete='RESTRICT'
    )

    # 3. mission_steps table
    op.drop_constraint('mission_steps_mission_template_id_fkey', 'mission_steps', type_='foreignkey')
    op.create_foreign_key(
        'mission_steps_mission_template_id_fkey', 'mission_steps', 'mission_templates',
        ['mission_template_id'], ['id'], ondelete='CASCADE'
    )

    # 4. mission_step_progress table
    op.drop_constraint('mission_step_progress_mission_progress_id_fkey', 'mission_step_progress', type_='foreignkey')
    op.create_foreign_key(
        'mission_step_progress_mission_progress_id_fkey', 'mission_step_progress', 'mission_progress',
        ['mission_progress_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint('mission_step_progress_mission_step_id_fkey', 'mission_step_progress', type_='foreignkey')
    op.create_foreign_key(
        'mission_step_progress_mission_step_id_fkey', 'mission_step_progress', 'mission_steps',
        ['mission_step_id'], ['id'], ondelete='RESTRICT'
    )

    # 5. phrase_step_mapping table
    op.drop_constraint('phrase_step_mapping_mission_step_id_fkey', 'phrase_step_mapping', type_='foreignkey')
    op.create_foreign_key(
        'phrase_step_mapping_mission_step_id_fkey', 'phrase_step_mapping', 'mission_steps',
        ['mission_step_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint('phrase_step_mapping_phrase_id_fkey', 'phrase_step_mapping', type_='foreignkey')
    op.create_foreign_key(
        'phrase_step_mapping_phrase_id_fkey', 'phrase_step_mapping', 'phrases',
        ['phrase_id'], ['id'], ondelete='CASCADE'
    )

    # 6. route_history table
    op.drop_constraint('route_history_profile_id_fkey', 'route_history', type_='foreignkey')
    op.create_foreign_key(
        'route_history_profile_id_fkey', 'route_history', 'profiles',
        ['profile_id'], ['id'], ondelete='CASCADE'
    )

    # 7. profiles.user_id FK to auth.users (Supabase)
    # Note: This FK is only created in production where auth.users exists.
    # For tests, we rely on application-level validation via Supabase Auth API.
    # The constraint is commented out and should be applied manually in production.
    #
    # Production command:
    # ALTER TABLE profiles ADD CONSTRAINT profiles_user_id_fkey
    #   FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
    pass  # FK to auth.users handled at application level


def downgrade() -> None:
    """Remove ON DELETE rules from foreign keys."""
    # Drop FK with CASCADE rule and recreate without
    # Note: This is simplified - in production, would need to handle carefully

    op.execute("ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey")

    # route_history
    op.drop_constraint('route_history_profile_id_fkey', 'route_history', type_='foreignkey')
    op.create_foreign_key('route_history_profile_id_fkey', 'route_history', 'profiles', ['profile_id'], ['id'])

    # phrase_step_mapping
    op.drop_constraint('phrase_step_mapping_phrase_id_fkey', 'phrase_step_mapping', type_='foreignkey')
    op.create_foreign_key('phrase_step_mapping_phrase_id_fkey', 'phrase_step_mapping', 'phrases', ['phrase_id'], ['id'])
    op.drop_constraint('phrase_step_mapping_mission_step_id_fkey', 'phrase_step_mapping', type_='foreignkey')
    op.create_foreign_key('phrase_step_mapping_mission_step_id_fkey', 'phrase_step_mapping', 'mission_steps', ['mission_step_id'], ['id'])

    # mission_step_progress
    op.drop_constraint('mission_step_progress_mission_step_id_fkey', 'mission_step_progress', type_='foreignkey')
    op.create_foreign_key('mission_step_progress_mission_step_id_fkey', 'mission_step_progress', 'mission_steps', ['mission_step_id'], ['id'])
    op.drop_constraint('mission_step_progress_mission_progress_id_fkey', 'mission_step_progress', type_='foreignkey')
    op.create_foreign_key('mission_step_progress_mission_progress_id_fkey', 'mission_step_progress', 'mission_progress', ['mission_progress_id'], ['id'])

    # mission_steps
    op.drop_constraint('mission_steps_mission_template_id_fkey', 'mission_steps', type_='foreignkey')
    op.create_foreign_key('mission_steps_mission_template_id_fkey', 'mission_steps', 'mission_templates', ['mission_template_id'], ['id'])

    # mission_progress
    op.drop_constraint('mission_progress_mission_template_id_fkey', 'mission_progress', type_='foreignkey')
    op.create_foreign_key('mission_progress_mission_template_id_fkey', 'mission_progress', 'mission_templates', ['mission_template_id'], ['id'])
    op.drop_constraint('mission_progress_profile_id_fkey', 'mission_progress', type_='foreignkey')
    op.create_foreign_key('mission_progress_profile_id_fkey', 'mission_progress', 'profiles', ['profile_id'], ['id'])

    # translations
    op.drop_constraint('translations_mission_progress_id_fkey', 'translations', type_='foreignkey')
    op.create_foreign_key('translations_mission_progress_id_fkey', 'translations', 'mission_progress', ['mission_progress_id'], ['id'])
    op.drop_constraint('translations_profile_id_fkey', 'translations', type_='foreignkey')
    op.create_foreign_key('translations_profile_id_fkey', 'translations', 'profiles', ['profile_id'], ['id'])
