from enum import StrEnum
from typing import Generic, TypeVar

from pydantic import BaseModel

T = TypeVar("T")


class Status(StrEnum):
    # 성공
    SUCCESS = "SUCCESS"

    # 인증 관련
    USER_AUTHENTICATION_FAILED = "USER_AUTHENTICATION_FAILED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # 사용자 관련
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    USER_DELETED = "USER_DELETED"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    # 권한 관련
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # 리소스 관련
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"

    # 장소 관련
    PLACE_NOT_FOUND = "PLACE_NOT_FOUND"
    LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND"

    # 경로 관련
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    ROUTE_SEARCH_FAILED = "ROUTE_SEARCH_FAILED"
    SAME_ORIGIN_DESTINATION = "SAME_ORIGIN_DESTINATION"

    # 즐겨찾기 관련
    FAVORITE_NOT_FOUND = "FAVORITE_NOT_FOUND"
    FAVORITE_ALREADY_EXISTS = "FAVORITE_ALREADY_EXISTS"

    # 가이드 관련
    SITUATION_NOT_FOUND = "SITUATION_NOT_FOUND"
    INTENT_NOT_FOUND = "INTENT_NOT_FOUND"
    GUIDE_NOT_FOUND = "GUIDE_NOT_FOUND"

    # 여정 관련
    JOURNEY_NOT_FOUND = "JOURNEY_NOT_FOUND"
    JOURNEY_ALREADY_ACTIVE = "JOURNEY_ALREADY_ACTIVE"
    JOURNEY_ALREADY_COMPLETED = "JOURNEY_ALREADY_COMPLETED"

    # 유효성 검사
    VALIDATION_FAILED = "VALIDATION_FAILED"

    # 인증/토큰 관련 (SPEC 기반)
    ERROR_UNAUTHORIZED = "ERROR_UNAUTHORIZED"
    ERROR_INVALID_TOKEN = "ERROR_INVALID_TOKEN"
    ERROR_FORBIDDEN = "ERROR_FORBIDDEN"
    ERROR_NOT_FOUND = "ERROR_NOT_FOUND"
    ERROR_VALIDATION = "ERROR_VALIDATION"

    # 번역 관련
    ERROR_INVALID_AUDIO = "ERROR_INVALID_AUDIO"
    TRANSLATION_NOT_FOUND = "TRANSLATION_NOT_FOUND"

    # 미션 관련
    MISSION_NOT_FOUND = "MISSION_NOT_FOUND"
    ERROR_MISSION_ALREADY_STARTED = "ERROR_MISSION_ALREADY_STARTED"
    ERROR_MISSION_NOT_STARTED = "ERROR_MISSION_NOT_STARTED"
    MISSION_PROGRESS_NOT_FOUND = "MISSION_PROGRESS_NOT_FOUND"
    MISSION_STEP_NOT_FOUND = "MISSION_STEP_NOT_FOUND"

    # 추천 문장 관련
    PHRASE_NOT_FOUND = "PHRASE_NOT_FOUND"

    # 경로 관련 (추가)
    ERROR_ROUTE_NOT_FOUND = "ERROR_ROUTE_NOT_FOUND"
    ERROR_TOO_MANY_WAYPOINTS = "ERROR_TOO_MANY_WAYPOINTS"

    # 서버 오류
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    TMAP_API_ERROR = "TMAP_API_ERROR"
    NAVER_API_ERROR = "NAVER_API_ERROR"


class ApiResponse(BaseModel, Generic[T]):
    status: Status
    message: str = ""
    data: T | None = None
